name: Slack 파일 업로드

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # 10분마다 실행

jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: Java 17 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Java 코드 실행 (Slack 파일 업로드)
        run: |
          javac SlackUploader.java
          java SlackUploader
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
